module.exports = [
  { clue: "What are two things you can never eat for breakfast?", answer: "Lunch and dinner." },
  { clue: "What is always coming but never arrives?", answer: "Tomorrow." },
  { clue: "What gets wetter the more it dries?", answer: "A towel." },
  { clue: "What can be broken but never held?", answer: "A promise." },
  { clue: "What word is spelled incorrectly in every dictionary?", answer: "Incorrectly." },
  { clue: "What lives if it is fed, and dies if you give it a drink?", answer: "Fire." },
  { clue: "What never asks a question but gets answered all the time?", answer: "Your cellphone." },
  { clue: "What has keys but cannot open locks?", answer: "A piano." },
  { clue: "What has hands but cannot clap?", answer: "A clock." },
  { clue: "What has a head and a tail but no body?", answer: "A coin." },
  { clue: "What can travel around the world while staying in one corner?", answer: "A stamp." },
  { clue: "What has one eye but cannot see?", answer: "A needle." },
  { clue: "What begins with T, ends with T, and has tea in it?", answer: "A teapot." },
  { clue: "Which month has 28 days?", answer: "All of them." },
  { clue: "What has many teeth but cannot bite?", answer: "A comb." },
  { clue: "What has a neck but no head?", answer: "A bottle." },
  { clue: "What runs but never walks?", answer: "A river." },
  { clue: "What gets bigger when more is taken away?", answer: "A hole." },
  { clue: "What has words but never speaks?", answer: "A book." },
  { clue: "What goes up but never comes down?", answer: "Your age." },
  { clue: "What goes through towns and over hills but never moves?", answer: "A road." },
  { clue: "What has legs but does not walk?", answer: "A table." },
  { clue: "What has a ring but no finger?", answer: "A telephone." },
  { clue: "What is full of holes but still holds water?", answer: "A sponge." },
  { clue: "What can you catch but never throw?", answer: "A cold." },
  { clue: "What has four wheels and flies?", answer: "A garbage truck." },
  { clue: "What kind of room has no doors or windows?", answer: "A mushroom." },
  { clue: "What building has the most stories?", answer: "A library." },
  { clue: "What can fill a room but takes no space?", answer: "Light." },
  { clue: "What has to be broken before you can use it?", answer: "An egg." },
  { clue: "What has one head, one foot, and four legs?", answer: "A bed." },
  { clue: "Before Mount Everest was discovered, what was the highest mountain?", answer: "Mount Everest." },
  { clue: "What kind of cup cannot hold water?", answer: "A cupcake." },
  { clue: "What has ears but cannot hear?", answer: "A cornfield." },
  { clue: "What kind of lion never roars?", answer: "A dandelion." },
  { clue: "What starts with P, ends with E, and has thousands of letters?", answer: "A post office." },
  { clue: "What starts with E, ends with E, and contains one letter?", answer: "An envelope." },
  { clue: "What comes once in a minute, twice in a moment, and never in a thousand years?", answer: "The letter M." },
  { clue: "What appears in the middle of March and April but nowhere else?", answer: "The letter R." },
  { clue: "If you drop a yellow hat into the Red Sea, what does it become?", answer: "Wet." },
  { clue: "If an electric train is moving south, which way does smoke go?", answer: "Nowhere. Electric trains do not make smoke." },
  { clue: "What can be cracked, made, told, and played?", answer: "A joke." },
  { clue: "What gets shorter as it gets older?", answer: "A candle." },
  { clue: "What has a thumb and four fingers but is not alive?", answer: "A glove." },
  { clue: "What is always in front of you but cannot be seen?", answer: "The future." },
  { clue: "What kind of tree can fit in your hand?", answer: "A palm tree." },
  { clue: "What has cities, rivers, and mountains but no houses?", answer: "A map." },
  { clue: "What can be heard but cannot be touched or seen?", answer: "Your voice." },
  { clue: "What comes down but never goes up?", answer: "Rain." },
  { clue: "What kind of band never plays music?", answer: "A rubber band." },
  { clue: "What kind of coat is best put on when wet?", answer: "A coat of paint." },
  { clue: "What invention lets you look right through a wall?", answer: "A window." },
  { clue: "What has a bottom at the top?", answer: "Your legs." },
  { clue: "What do you throw out when you want to use it and take in when done?", answer: "An anchor." },
  { clue: "What can you hold in your right hand but never in your left hand?", answer: "Your left elbow." },
  { clue: "What kind of bow cannot be tied?", answer: "A rainbow." },
  { clue: "What has branches but no fruit, trunk, or leaves?", answer: "A bank." },
  { clue: "What has many eyes but cannot see?", answer: "A potato." },
  { clue: "What has an eye but cannot see anything?", answer: "A hurricane." },
  { clue: "What has keys but no rooms, and space but no place?", answer: "A keyboard." },
  { clue: "What can you keep after giving it to someone?", answer: "Your word." },
  { clue: "What goes from Z to A?", answer: "The alphabet." },
  { clue: "What has many needles but never sews?", answer: "A pine tree." },
  { clue: "What has a face but no eyes, nose, or mouth?", answer: "A clock." },
  { clue: "What is so fragile that saying its name breaks it?", answer: "Silence." },
  { clue: "What has 13 hearts but no other organs?", answer: "A deck of cards." },
  { clue: "Why do skeletons not fight each other?", answer: "They do not have the guts." },
  { clue: "What do you call fake spaghetti?", answer: "An impasta." },
  { clue: "Why did the scarecrow win an award?", answer: "He was outstanding in his field." },
  { clue: "What do you call cheese that is not yours?", answer: "Nacho cheese." },
  { clue: "Why could the bicycle not stand up?", answer: "It was two-tired." },
  { clue: "What do you call a bear with no teeth?", answer: "A gummy bear." },
  { clue: "Why did the math book look sad?", answer: "It had too many problems." },
  { clue: "What did the ocean say to the beach?", answer: "Nothing, it just waved." },
  { clue: "Why did the golfer bring extra pants?", answer: "In case he got a hole in one." },
  { clue: "What do you call a sleeping bull?", answer: "A bulldozer." },
  { clue: "Why do eggs not tell jokes?", answer: "They would crack each other up." },
  { clue: "What do you call a can opener that does not work?", answer: "A cannot opener." },
  { clue: "Why did the cookie go to the hospital?", answer: "Because it felt crummy." },
  { clue: "What do you call an alligator in a vest?", answer: "An investigator." },
  { clue: "Why did the tomato blush?", answer: "Because it saw the salad dressing." },
  { clue: "What do you call a fish with no eyes?", answer: "Fsh." },
  { clue: "Why can your nose not be 12 inches long?", answer: "Because then it would be a foot." },
  { clue: "What do you call a dinosaur with a huge vocabulary?", answer: "A thesaurus." },
  { clue: "Why did the picture go to jail?", answer: "Because it was framed." },
  { clue: "What do you call a snowman with a six-pack?", answer: "An abdominal snowman." },
  { clue: "Why did the bee have sticky hair?", answer: "It used a honeycomb." },
  { clue: "What do you call a boomerang that does not come back?", answer: "A stick." },
  { clue: "What kind of shoes do ninjas wear?", answer: "Sneakers." },
  { clue: "Why was the broom late?", answer: "It over-swept." },
  { clue: "What do you call a cow with no legs?", answer: "Ground beef." },
  { clue: "Why was the calendar always worried?", answer: "Its days were numbered." },
  { clue: "What did one eye say to the other eye?", answer: "Between us, something smells." },
  { clue: "Why do oysters not donate to charity?", answer: "Because they are shellfish." },
  { clue: "What do you call a pig that does karate?", answer: "A pork chop." },
  { clue: "Why did the duck get a timeout?", answer: "It kept quacking jokes in class." },
  { clue: "What do you call a magician's dog?", answer: "A labracadabrador." },
  { clue: "Why did the banana go to the doctor?", answer: "Because it was not peeling well." },
  { clue: "What do you call a belt made of watches?", answer: "A waist of time." },
  { clue: "Why are ghosts terrible liars?", answer: "Because you can see right through them." }
];

